name: "Let's Encrypt"
description: |
  Trusted SSL certificates at zero cost
version: 0.2.9
category: Security
maintainer: "Jan B. <jan@festplatte.eu.org>"
license: The MIT License
projectURL: http://www.github.com/janeczku/rancher-letsencrypt
